name: Validate Examples

on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  verify-objects:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: [curation, eln, experimental, figure_description, projects, source, system]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: { submodules: recursive }
      - name: Prepare json Files for Local Validation
        shell: bash -l {0}
        run: |
          find . -type f -name "*.json" -exec sed -i '/$id/d' {} +
      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          pip install check-jsonschema
      - name: Check Schemas
        shell: bash -l {0}
        run: |
          check-jsonschema --schemafile ./schemas/${{ matrix.file }}.json ./examples/objects/${{ matrix.file }}.yaml

  verify-file-schemas:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: [autotag, svgdigitizer]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: { submodules: recursive }
      - name: Prepare json Files for Local Validation
        shell: bash -l {0}
        run: |
          find . -type f -name "*.json" -exec sed -i '/$id/d' {} +
      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          pip install check-jsonschema
      - name: Check Schemas
        shell: bash -l {0}
        run: |
          check-jsonschema --schemafile ./schemas/${{ matrix.file }}.json ./examples/file_schemas/${{ matrix.file }}.yaml
